import pygame

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
MAX_LIVES = 6
FONT_NAME = None
FONT_SIZE_LARGE = 48
FONT_SIZE_MEDIUM = 32
FONT_SIZE_SMALL = 24
BUTTON_WIDTH = 40
BUTTON_HEIGHT = 40
BUTTON_MARGIN = 5

# Sound settings
SOUND_ENABLED = True
SOUND_VOLUME = 0.5

pygame.init()