# settings.py
import pygame

BASE_WIDTH = 1280
BASE_HEIGHT = 800
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 800

FPS = 60
MAX_LIVES = 6
HINT_COST = 50

BASE_FONT_HUGE = 72
BASE_FONT_LARGE = 48
BASE_FONT_MEDIUM = 32
BASE_FONT_SMALL = 22
BASE_FONT_TINY = 16

FONT_SIZE_HUGE = 72
FONT_SIZE_LARGE = 48
FONT_SIZE_MEDIUM = 32
FONT_SIZE_SMALL = 22
FONT_SIZE_TINY = 16

BUTTON_WIDTH = 54
BUTTON_HEIGHT = 54
BUTTON_MARGIN = 10
BUTTON_RADIUS = 14

SOUND_ENABLED = True
SOUND_VOLUME = 0.5

IS_FULLSCREEN = False

pygame.init()
pygame.mixer.init()

def update_font_sizes():
    global FONT_SIZE_HUGE, FONT_SIZE_LARGE, FONT_SIZE_MEDIUM, FONT_SIZE_SMALL, FONT_SIZE_TINY
    scale_x = SCREEN_WIDTH / BASE_WIDTH
    scale_y = SCREEN_HEIGHT / BASE_HEIGHT
    scale = min(scale_x, scale_y)
    
    FONT_SIZE_HUGE = int(BASE_FONT_HUGE * scale)
    FONT_SIZE_LARGE = int(BASE_FONT_LARGE * scale)
    FONT_SIZE_MEDIUM = int(BASE_FONT_MEDIUM * scale)
    FONT_SIZE_SMALL = int(BASE_FONT_SMALL * scale)
    FONT_SIZE_TINY = int(BASE_FONT_TINY * scale)